safe: true
lsi: false
highlighter: true
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_css: class
source: .
destination: ./_site
permalink: /:year/:month/:day/:title
exclude: ['README.md', '.gitignore', 'Gemfile', 'Gemfile.lock']
name: rousseau.io
description: rousseau.io
url: http://rousseau.io
